(()=>{'use strict';
const d=JSON.parse(document.getElementById('data').textContent),$=id=>document.getElementById(id),colors=['#087f8c','#e5a144','#596db1'];let view='overview',picked=new Set();
const el=(t,s,c)=>{const n=document.createElement(t);if(s!=null)n.textContent=s;if(c)n.className=c;return n;};
const safeUrl=u=>{try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)?x.href:null;}catch{return null;}};
function link(u,s){const a=el('a',s);const url=safeUrl(u);if(url){a.href=url;a.target='_blank';a.rel='noopener noreferrer';}return a;}
function field(dl,k,v){if(!v)return;dl.append(el('dt',k),el('dd',v));}
function sourceLinks(x,out){const links=el('div',null,'sources');if(x.url)links.append(link(x.url,'原始来源'));(x.sources||[]).forEach(s=>links.append(link(s.url,s.label)));out.append(links);}
function show(title,content){$('detail-title').textContent=title;$('detail-body').replaceChildren(content);$('detail').showModal();}
function recordDetail(x,type){const out=el('div'),dl=el('dl');out.append(el('span',x.id,'tag'));if(type==='company'){field(dl,'路线与产品',x.route);field(dl,'最新证据（保留原来源口径）',x.fact);field(dl,'证据边界与未知',x.gap);field(dl,'对芯灵的竞争关系（分析）',x.relation);field(dl,'来源与可读状态',x.source);const ps=d.products.filter(p=>matchesCompany(x,p.company));if(ps.length){const box=el('div');box.append(el('h3','关联产品证据'));ps.forEach(p=>{const b=el('button',p.id+' '+p.product+' · '+p.stage,'btn');b.style.margin='4px';b.onclick=()=>recordDetail(p,'products');box.append(b);});out.append(box);}}else if(type==='products'){field(dl,'主体',x.company);field(dl,'阶段分类（分析）',x.stage);field(dl,'证据类型／原始口径',x.evidence);field(dl,'尚未证明',x.gap);field(dl,'事件日期',x.event||'未知');}else if(type==='events'){field(dl,'事件日期',x.date||(x.eventMonth?x.eventMonth+'（仅月份）':'未知'));field(dl,'事件及原始口径',x.event);field(dl,'证据边界',x.boundary);}else{field(dl,'路线',x.route);field(dl,'作者报告指标',x.metric);field(dl,'证据类型',x.evidence);field(dl,'范围与限制',x.boundary);}field(dl,'发布日期',x.publication||x.published||'未知／动态页面');field(dl,'检索日期',x.retrieved||d.snapshot);out.append(dl);sourceLinks(x,out);if($('detail').open)$('detail').close();show(x.name||x.product,out);}
function matchesCompany(c,n){const token=c.name.split(/[／（\s]/)[0].toLowerCase();return (n||'').toLowerCase().includes(token)||c.name.includes(n);}
function card(x,type){const c=el('article',null,'card');c.append(el('span',x.id,'id'));if(type==='company')c.append(el('span',x.group,'tag'));if(type==='products')c.append(el('span',x.stage,'tag'));if(type==='events')c.append(el('span',x.date||x.eventMonth||'事件日未知','tag'));c.append(el('h3',type==='products'?x.product:x.name));c.append(el('p',type==='company'?x.route:type==='products'?x.company:type==='events'?x.event:x.route));const text=type==='company'?x.fact:type==='products'?x.evidence:type==='events'?x.boundary:x.evidence;c.append(el('p',text,'meta'));const actions=el('div',null,'card-actions'),b=el('button','查看证据','btn');b.onclick=()=>recordDetail(x,type);actions.append(b);if(type==='company'){const lab=el('label',null,'check'),cb=el('input');cb.type='checkbox';cb.checked=picked.has(x.id);cb.setAttribute('aria-label','对比 '+x.name);cb.onchange=()=>{if(cb.checked&&picked.size>=3){cb.checked=false;show('最多对比 3 个主体',el('p','请先移除一个已选主体。'));return;}cb.checked?picked.add(x.id):picked.delete(x.id);compareBar();};lab.append(cb,document.createTextNode('加入对比'));actions.append(lab);}c.append(actions);return c;}
function compareBar(){$('comparebar').hidden=!picked.size;$('comparecount').textContent='已选 '+picked.size+' / 3';}
function render(){const q=$('query').value.trim().toLowerCase(),g=$('group-filter').value,s=$('stage-filter').value;let rows=d[view]||[];rows=rows.filter(x=>{if(q&&!JSON.stringify(x).toLowerCase().includes(q))return false;if(g){if(view==='company'&&x.group!==g)return false;if(view==='products'&&!d.company.some(c=>c.group===g&&matchesCompany(c,x.company)))return false;}if(s){if(view==='products'&&x.stage!==s)return false;if(view==='company'&&!d.products.some(p=>p.stage===s&&matchesCompany(x,p.company)))return false;}return true;});if(view==='events')rows=rows.slice().sort((a,b)=>(b.date||b.eventMonth||b.published||'').localeCompare(a.date||a.eventMonth||a.published||''));$('resultcount').textContent=rows.length+' 条匹配记录 · 点击查看编号、证据和原文';$('results').classList.toggle('timeline',view==='events');$('results').replaceChildren(...rows.map(x=>card(x,view)));if(!rows.length)$('results').append(el('p','没有匹配结果。试试减少筛选条件。','empty'));}
function go(v,reset=true){view=v;$('overview').hidden=v!=='overview';$('explore').hidden=v==='overview';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.view===v)));if(v!=='overview'){if(reset){$('query').value='';$('group-filter').value='';$('stage-filter').value='';}$('explore-title').textContent=({company:'竞争者与合作生态',products:'产品与商业阶段',events:'行业动态追溯',research:'科研验证与能力边界'})[v];$('group-label').hidden=!['company','products'].includes(v);$('stage-label').hidden=!['company','products'].includes(v);render();}history.replaceState(null,'','#'+v);window.scrollTo({top:0,behavior:'instant'});}
function bars(host,rows,click){const max=Math.max(...rows.map(x=>x.value));rows.forEach(x=>{const b=el('button',null,'bar'),track=el('span',null,'track'),fill=el('span',null,'fill');fill.style.width=x.value/max*100+'%';track.append(fill);b.append(el('span',x.label),track,el('b',x.value));b.setAttribute('aria-label',x.label+' '+x.value+'，查看证据');b.onclick=()=>click(x);host.append(b);});}
$('snapshot').textContent='证据快照 '+d.snapshot+' · '+(d.snapshotTime||'')+' · 非实时行情';
[['竞争主体',d.company.length,'company'],['产品证据',d.products.length,'products'],['关键事件',d.events.length,'events'],['科研记录',d.research.length,'research']].forEach(([s,n,v])=>{const b=el('button',null,'stat');b.append(el('b',n),el('span',s));b.onclick=()=>go(v);$('stats').append(b);});
const aggregate=(rows,key)=>Object.entries(rows.reduce((acc,x)=>{const label=x[key]||'未分类';acc[label]=(acc[label]||0)+1;return acc;},{})).map(([label,value])=>({label,value}));
bars($('groups'),aggregate(d.company,'group'),x=>{go('company');$('group-filter').value=x.label;render();});bars($('stages'),aggregate(d.products,'stage'),x=>{go('products');$('stage-filter').value=x.label;render();});
[...new Set(d.company.map(x=>x.group))].forEach(s=>$('group-filter').append(new Option(s,s)));[...new Set(d.products.map(x=>x.stage))].forEach(s=>$('stage-filter').append(new Option(s,s)));
const fmt=v=>v.toLocaleString('en-US'),max=Math.max(...[2025,2026].map(y=>d.financial.reduce((s,x)=>s+x['v'+y],0)));[2025,2026].forEach(y=>{const row=el('div',null,'finance-row'),sum=d.financial.reduce((s,x)=>s+x['v'+y],0);row.append(el('strong',y+' H1 · US$ '+fmt(sum)));const stack=el('div',null,'stack');stack.style.width=sum/max*100+'%';d.financial.forEach((x,i)=>{const b=el('span');b.style.width=x['v'+y]/sum*100+'%';b.style.background=colors[i];b.title=x.label+' US$'+fmt(x['v'+y]);stack.append(b);});row.append(stack,el('div',d.financial.map(x=>x.label+' '+fmt(x['v'+y])).join(' · '),'meta'));$('finance').append(row);});const leg=el('div',null,'legend');d.financial.forEach((x,i)=>{const n=el('span',x.label),m=el('i');m.style.background=colors[i];n.prepend(m);leg.append(n);});$('finance').append(leg);d.liquidity.forEach(x=>{const row=el('div',null,'finance-row');row.append(el('strong',x.label+' · '+(x.unit==='颗'?fmt(x.value)+' 颗':'US$ '+fmt(x.value))),el('div',x.note,'meta'));$('finance').append(row);});$('finance-source').href=d.financeSource;
d.consolidation.forEach(x=>{const n=el('div',null,'finance-row');n.append(el('span',x.date,'meta'),el('h3',x.subject),el('p',x.status),el('p',x.boundary,'meta'),link(x.url,'原始证据'));$('mergers').append(n);});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));['query','group-filter','stage-filter'].forEach(id=>$(id).addEventListener(id==='query'?'input':'change',render));$('reset').onclick=()=>{['query','group-filter','stage-filter'].forEach(id=>$(id).value='');render();};$('close').onclick=()=>$('detail').close();$('detail').addEventListener('click',e=>{if(e.target===$('detail'))$('detail').close();});$('clearcompare').onclick=()=>{picked.clear();compareBar();if(view==='company')render();};$('compare').onclick=()=>{const out=el('div',null,'compare-grid');d.company.filter(x=>picked.has(x.id)).forEach(x=>{const sec=el('section'),dl=el('dl');sec.append(el('span',x.id,'id'),el('h3',x.name));field(dl,'分层',x.group);field(dl,'路线',x.route);field(dl,'已知证据',x.fact);field(dl,'缺口',x.gap);field(dl,'竞争关系（分析）',x.relation);sec.append(dl);sourceLinks(x,sec);out.append(sec);});show('竞争证据对比',out);};
const start=location.hash.slice(1);go(['company','products','events','research'].includes(start)?start:'overview');
})();
