import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
const root=path.dirname(fileURLToPath(import.meta.url));
const data=JSON.parse(fs.readFileSync(path.join(root,'evidence.json'),'utf8'));
data.history=JSON.parse(fs.readFileSync(path.join(root,'history-model.json'),'utf8'));
data.taxonomy=JSON.parse(fs.readFileSync(path.join(root,'landscape-taxonomy.json'),'utf8'));
const historyApp=fs.readFileSync(path.join(root,'company-history.js'),'utf8');
const appVersion=createHash('sha256').update(fs.readFileSync(path.join(root,'app.js'))).update(historyApp).digest('hex').slice(0,12);
const html=fs.readFileSync(path.join(root,'web-template.html'),'utf8').replace('__DATA__',JSON.stringify(data).replaceAll('<','\\u003c')).replaceAll('__APP_VERSION__',appVersion);
for(const name of ['index.html','dashboard.html'])fs.writeFileSync(path.join(root,name),html);
const app=fs.readFileSync(path.join(root,'app.js'),'utf8').replaceAll('</script>','<\\/script>');
const visualization=html.replace(/<script src="company-history\.js\?v=[^"]+"><\/script>/,`<script>${historyApp}</script>`).replace(/<script src="app\.js\?v=[^"]+"><\/script>/,`<script>${app}</script>`);
fs.writeFileSync(path.join(root,'visualization.html'),visualization);
const esc=(value)=>String(value??'—').replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const link=(url,label='原文')=>url?`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(label)}</a>`:'—';
const rows=(items,fields)=>items.map(item=>`<tr>${fields.map(field=>`<td data-label="${esc(field.label)}">${field.render?field.render(item):esc(item[field.key])}</td>`).join('')}</tr>`).join('');
const table=(items,fields)=>`<div class="table-wrap"><table><thead><tr>${fields.map(field=>`<th>${esc(field.label)}</th>`).join('')}</tr></thead><tbody>${rows(items,fields)}</tbody></table></div>`;
const report=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>类脑芯片市场证据报告</title><style>
:root{color-scheme:light;--ink:#172c3b;--muted:#5d6d78;--line:#cbd8df;--paper:#f7fafc;--card:#fff;--accent:#126b92}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}nav{position:sticky;top:0;z-index:2;display:flex;gap:14px;overflow:auto;padding:12px 16px;background:rgba(247,250,252,.96);border-bottom:1px solid var(--line);white-space:nowrap}a{color:var(--accent)}main{max-width:1280px;margin:auto;padding:20px}.hero,.card,details{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:18px;margin:0 0 16px}.hero h1{margin:.1em 0}.muted{color:var(--muted)}.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:16px 0}.kpi{padding:14px;border-radius:12px;background:#eaf4f8}.kpi b{display:block;font-size:28px}.callout{border-left:4px solid var(--accent);padding:10px 14px;background:#eef7fa}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:10px}table{border-collapse:collapse;width:100%;min-width:840px}th,td{padding:10px;vertical-align:top;border-bottom:1px solid var(--line);text-align:left}th{background:#eaf1f5;position:sticky;top:45px}details>summary{cursor:pointer;font-weight:700;font-size:18px}details[open]>summary{margin-bottom:14px}.tag{display:inline-block;padding:2px 7px;border-radius:999px;background:#eaf4f8;font-size:12px}@media(max-width:700px){main{padding:12px}.kpis{grid-template-columns:repeat(2,1fr)}.hero,.card,details{padding:14px}table{min-width:0}thead{display:none}tr{display:block;border-bottom:8px solid var(--paper)}td{display:grid;grid-template-columns:7.6em 1fr;gap:8px;border-bottom:1px solid var(--line)}td:before{content:attr(data-label);font-weight:700;color:var(--muted)}th{position:static}}
</style></head><body><nav><a href="index.html">交互分析</a><a href="market-evidence.xlsx">Excel数据</a><a href="evidence.json">JSON证据</a><a href="https://github.com/v5qqskzkhj-ship-it/neuromorphic-market-report">版本历史</a></nav><main><section class="hero"><p class="muted">证据快照 ${esc(data.snapshotTime)}</p><h1>类脑芯片市场证据报告</h1><p>覆盖核心SNN、事件视觉、模拟AI／存算、机器人触觉与多模态、在线学习、传统端侧替代及国内类脑模型／世界模型生态。样本数量不代表市场份额。</p><div class="kpis"><div class="kpi"><b>${data.company.length}</b>竞争主体</div><div class="kpi"><b>${data.products.length}</b>产品证据</div><div class="kpi"><b>${data.events.length}</b>行业事件</div><div class="kpi"><b>${data.research.length}</b>研究记录</div></div><p class="callout"><strong>本轮判断：</strong>BrainChip已把公开能力面从单芯片／开发板延伸到多卡Akida调度与常开感知预订方案；公开代码和参考硬件提高了工具链与复现门槛，但尚无企业客户部署、付费合同、收入或独立性能验证。</p></section><section class="card"><h2>证据边界</h2><p>融资不计收入；预订不计出货；公开仓库不计企业部署；厂商参考结果不计独立基准；事件传感、模拟AI和存算一体不自动归为SNN。事件日期、发布日期与检索日期分列，未知值保持空白。</p></section><details open><summary>竞争主体（${data.company.length}）</summary>${table(data.company,[{label:'编号',key:'id'},{label:'主体',key:'name'},{label:'分层',key:'group'},{label:'路线',key:'route'},{label:'已核事实',key:'fact'},{label:'证据缺口',key:'gap'},{label:'来源',render:item=>link(item.url)}])}</details><details><summary>产品与交付阶段（${data.products.length}）</summary>${table(data.products,[{label:'编号',key:'id'},{label:'主体',key:'company'},{label:'产品',key:'product'},{label:'阶段',render:item=>`<span class="tag">${esc(item.stage)}</span>`},{label:'证据',key:'evidence'},{label:'边界',render:item=>esc(item.boundary||item.gap)},{label:'来源',render:item=>link(item.url)}])}</details><details><summary>行业事件（${data.events.length}）</summary>${table(data.events,[{label:'编号',key:'id'},{label:'事件日',render:item=>esc(item.date||item.eventMonth)},{label:'发布日期',key:'published'},{label:'主体',key:'name'},{label:'事件',key:'event'},{label:'边界',key:'boundary'},{label:'来源',render:item=>link(item.url)}])}</details><details><summary>研究与科研平台（${data.research.length}）</summary>${table(data.research,[{label:'编号',key:'id'},{label:'项目',key:'name'},{label:'发布日期',key:'publication'},{label:'证据',key:'evidence'},{label:'指标',key:'metric'},{label:'边界',key:'boundary'},{label:'来源',render:item=>link(item.url)}])}</details></main></body></html>`;
fs.writeFileSync(path.join(root,'report.html'),report);
console.log(`Generated ${data.company.length} companies / ${data.products.length} products.`);
