function buildCompanyHistory(d,el,recordDetail,show,sourceLinks,matchesCompany){
 'use strict';
 const model=d.history,tax=d.taxonomy;if(!model||!tax)return;
 const palette={'产品／研发':'#087f8c','客户／部署':'#3066ad','融资':'#b47a14','合作／IP':'#8055a7','战略／整合':'#bc5865'},symbols={'产品／研发':'●','客户／部署':'■','融资':'◆','合作／IP':'▲','战略／整合':'✚'};
 const companies=new Map(d.company.map(c=>[c.id,c])),region=c=>Object.keys(tax.regionSets).find(r=>tax.regionSets[r].includes(c.id))||'区位待核';
 const sector=c=>model.primarySector[c.id]||'板块待核';
 const owner=x=>d.company.filter(c=>matchesCompany(c,x.company||x.name));
 function dateInfo(value){if(!value)return null;const m=String(value).match(/^(\d{4})-(\d{2})(?:-(\d{2}))?$/);if(!m)return null;return {t:Date.UTC(+m[1],+m[2]-1,m[3]?+m[3]:15),text:value,monthOnly:!m[3]};}
 const evidence=[];
 d.events.forEach(e=>evidence.push({key:e.id,date:dateInfo(e.date||e.eventMonth),owners:owner(e).map(c=>c.id),type:model.eventTypes[e.id]||'产品／研发',title:e.event,record:e,kind:'events'}));
 d.products.forEach(p=>evidence.push({key:p.id,date:dateInfo(p.event),owners:owner(p).map(c=>c.id),type:'产品／研发',title:p.product+' · '+p.stage,record:p,kind:'products'}));
 d.consolidation.forEach((c,i)=>String(c.date).split('／').forEach((dt,j)=>evidence.push({key:'K'+String(i+1).padStart(3,'0')+(j?'-'+(j+1):''),date:dateInfo(dt),owners:model.consolidationOwners[i]||[],type:'战略／整合',title:c.subject+' · '+c.status,record:c,kind:'consolidation'})));
 const ref=r=>evidence.find(e=>r.event?e.key===r.event:r.product?e.key===r.product:e.key==='K'+String(r.consolidation+1).padStart(3,'0'));
 const relationships=model.relations.map(r=>({...r,evidence:ref(r)})).filter(r=>r.evidence?.date);
 // Explicit relation targets supplement abbreviated record names without treating partners as competitors.
 relationships.forEach(r=>{for(const id of [r.from,r.to])if(!r.evidence.owners.includes(id))r.evidence.owners.push(id);});
 const root=el('section',null,'history panel');root.id='company-history';root.append(el('p','同一时间尺度 · 每家公司一行 · 有证据的关系才连线','sectionlabel'),el('h2','类脑产业演化图'));
 const controls=el('div',null,'history-controls');const state={group:'sector',range:'2026',query:'',region:'',sector:'',selected:'',focus:false,dated:false,links:true};
 function select(key,label,options){const l=el('label',label),s=el('select');s.setAttribute('aria-label',label);options.forEach(([v,t])=>s.append(new Option(t,v)));s.value=state[key];s.onchange=()=>{state[key]=s.value;draw();};l.append(s);controls.append(l);return s;}
 select('group','公司排列',[['sector','按商业板块分组'],['region','按区位分组'],['layer','按芯片／模型／替代分层']]);
 select('range','共同时间范围',[['2026','2026全年'],['h2','2026下半年（放大）'],['all','2023—2026全部记录']]);
 select('region','区位筛选',[['','全部区位'],...Object.keys(tax.regionSets).map(r=>[r,r]),['区位待核','区位待核']]);
 select('sector','板块筛选',[['','全部板块'],...Object.keys(tax.sectorSets).map(s=>[s,s])]);
 const qlabel=el('label','搜索公司／关联方'),query=el('input');query.type='search';query.placeholder='例如：BrainChip、世界模型、Mythic';query.oninput=()=>{state.query=query.value.trim().toLowerCase();draw();};qlabel.append(query);controls.append(qlabel);root.append(controls);
 const switches=el('div',null,'history-switches');[['links','显示关系连线'],['dated','仅显示有日期的主体'],['focus','聚焦选中公司及关联方']].forEach(([k,label])=>{const lab=el('label'),cb=el('input');cb.type='checkbox';cb.checked=state[k];cb.onchange=()=>{state[k]=cb.checked;draw();};lab.append(cb,document.createTextNode(label));switches.append(lab);});const clear=el('button','取消公司选择','btn');clear.onclick=()=>{state.selected='';draw();};switches.append(clear);root.append(switches);
 const legend=el('div',null,'legend history-legend');Object.entries(palette).forEach(([type,color])=>{const s=el('span',symbols[type]+' '+type);s.style.color=color;legend.append(s);});legend.append(el('span','空心节点＝仅知道月份；密集节点合并后点开'));root.append(legend);
 const status=el('p',null,'note');status.setAttribute('aria-live','polite');const summary=el('div',null,'history-selection');root.append(status,summary);
 const viewport=el('div',null,'history-viewport'),canvas=el('div',null,'history-canvas');viewport.append(canvas);root.append(viewport);
 viewport.addEventListener('scroll',()=>pinLabels(),{passive:true});
 function pinLabels(){canvas.querySelectorAll('.history-label,.history-axis-label').forEach(n=>n.style.transform='translateX('+viewport.scrollLeft+'px)');}
 const unknown=el('details');unknown.append(el('summary','日期未知的证据与历史覆盖缺口'));const gaps=el('div');unknown.append(gaps);root.append(unknown);
 const note=el('p','横轴为事件日期，纵轴为主体。灰色横线仅用于时间对齐，不表示成立、存续或持续量产。分组依据当前板块／区位，不能从分组反推历史归属；战略转向通过证据节点表达。空白年份表示未收录证据，不表示公司没有活动。关联方不计竞争主体；融资、客户部署与收入保持区分。','meta');root.append(note);
 const download=el('a','下载关系映射与证据编号');download.href='https://v5qqskzkhj-ship-it.github.io/neuromorphic-market-report/history-model.json';root.append(download);
 document.getElementById('overview').prepend(root);
 function detail(items,title){const out=el('div');items.slice().sort((a,b)=>(a.date?.t||Infinity)-(b.date?.t||Infinity)).forEach(e=>{const row=el('div',null,'finance-row');const dateLabel=e.date?e.date.text+(e.date.monthOnly?'（仅月份）':''):'事件日未知';row.append(el('span',e.key+' · '+dateLabel+' · '+e.type,'meta'),el('p',e.title));const b=el('button','展开原文与证据边界','btn');b.onclick=()=>{if(e.kind!=='consolidation'){document.getElementById('detail').close();recordDetail(e.record,e.kind);}else{const body=el('div');body.append(el('p',e.record.subject),el('p','表内日期：'+e.record.date),el('p',e.record.status),el('p',e.record.boundary,'note'));sourceLinks(e.record,body);document.getElementById('detail').close();show(e.record.subject,body);}};row.append(b);out.append(row);});if(document.getElementById('detail').open)document.getElementById('detail').close();show(title,out);}
 function draw(){
  const end=Date.UTC(2026,9,3),start=state.range==='all'?Date.UTC(2023,0,1):state.range==='h2'?Date.UTC(2026,6,1):Date.UTC(2026,0,1);
  const inRange=e=>e.date&&e.date.t>=start&&e.date.t<=end;
  const relevant=evidence.filter(inRange),selNeighbors=new Set([state.selected,...relationships.filter(r=>[r.from,r.to].includes(state.selected)&&inRange(r.evidence)).flatMap(r=>[r.from,r.to])]);
  const sharedPartners=new Set([...selNeighbors].filter(id=>id.startsWith('X-')));relationships.filter(r=>inRange(r.evidence)&&(sharedPartners.has(r.from)||sharedPartners.has(r.to))).forEach(r=>{selNeighbors.add(r.from);selNeighbors.add(r.to);});
  let cs=d.company.filter(c=>(!state.region||region(c)===state.region)&&(!state.sector||(tax.sectorSets[state.sector]||[]).includes(c.id))&&(!state.query||(c.name+' '+c.route).toLowerCase().includes(state.query))&&(!state.dated||relevant.some(e=>e.owners.includes(c.id)))&&(!state.focus||!state.selected||selNeighbors.has(c.id)));
  // External partner search includes linked companies so relationships remain inspectable.
  if(state.query&&cs.length===0){const partnerIds=Object.entries(model.partners).filter(([,n])=>n.toLowerCase().includes(state.query)).map(([id])=>id);const targets=new Set(relationships.filter(r=>partnerIds.includes(r.from)||partnerIds.includes(r.to)).flatMap(r=>[r.from,r.to]));cs=d.company.filter(c=>targets.has(c.id));}
  const group=c=>state.group==='sector'?sector(c):state.group==='region'?region(c):c.group;
  cs.sort((a,b)=>group(a).localeCompare(group(b),'zh-CN')||a.id.localeCompare(b.id));
  const companyIds=new Set(cs.map(c=>c.id));const rs=state.links?relationships.filter(r=>inRange(r.evidence)&&(companyIds.has(r.from)||companyIds.has(r.to))):[];
  const outside=[...new Set(rs.flatMap(r=>[r.from,r.to]).filter(id=>!companyIds.has(id)))].filter(id=>model.partners[id]||companies.has(id));
  // Include standalone exit history (GrAI/Snap) only in the full historical overview.
  if(state.range==='all'&&state.links&&!state.query&&!state.region&&!state.sector&&!state.focus){const exit=relationships.filter(r=>r.from==='X-GRAI');exit.forEach(r=>{rs.push(r);for(const id of [r.from,r.to])if(!outside.includes(id))outside.push(id);});}
  const rows=[],ys=new Map();let lastGroup='';cs.forEach(c=>{const g=group(c);if(g!==lastGroup){rows.push({heading:g});lastGroup=g;}rows.push({id:c.id,name:c.name,meta:region(c)+' · '+c.group});});if(outside.length){rows.push({heading:'关联方／历史退出主体（不计竞争主体）'});outside.forEach(id=>rows.push({id,name:companies.get(id)?.name||model.partners[id],meta:companies.has(id)?'另一板块的已收录主体':'仅作为合作／交易关联方'}));}
  const lane=62,header=44,left=window.innerWidth<=700?138:182,width=state.range==='all'?1420:1120,timeWidth=width-left-34,scale=t=>left+(t-start)/(end-start)*timeWidth;
  let height=header;rows.forEach(row=>{row.y=height;row.height=row.heading?34:lane;if(row.id)ys.set(row.id,height+lane/2);height+=row.height;});
  canvas.replaceChildren();canvas.style.width=width+'px';canvas.style.height=Math.max(160,height)+'px';
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width',width);svg.setAttribute('height',height);svg.setAttribute('aria-hidden','true');svg.classList.add('history-lines');canvas.append(svg);
  function shape(tag,attrs){const n=document.createElementNS(svg.namespaceURI,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));svg.append(n);return n;}
  for(let t=Date.UTC(new Date(start).getUTCFullYear(),new Date(start).getUTCMonth(),1);t<=end;){const x=scale(t);shape('line',{x1:x,y1:header,x2:x,y2:height,stroke:'#dce5eb','stroke-width':1});t=Date.UTC(new Date(t).getUTCFullYear(),new Date(t).getUTCMonth()+1,1);}
  rows.forEach(row=>{if(row.heading){const h=el('div',row.heading,'history-band');h.style.top=row.y+'px';h.style.height=row.height+'px';h.style.width=width+'px';canvas.append(h);}else{shape('line',{x1:left,y1:ys.get(row.id),x2:width-20,y2:ys.get(row.id),stroke:state.selected===row.id?'#829bac':'#edf1f4','stroke-width':1});const label=el('button',null,'history-label');label.style.top=row.y+'px';label.style.height=lane+'px';label.setAttribute('aria-pressed',String(state.selected===row.id));label.append(el('strong',row.name),el('small',row.meta));label.onclick=()=>{state.selected=state.selected===row.id?'':row.id;draw();};canvas.append(label);}});
  rs.forEach((r,i)=>{if(!ys.has(r.from)||!ys.has(r.to))return;const x=scale(r.evidence.date.t),y1=ys.get(r.from),y2=ys.get(r.to),bend=18+(i%4)*9,isSelected=!state.selected||(selNeighbors.has(r.from)&&selNeighbors.has(r.to));shape('path',{d:`M ${x} ${y1} C ${x+bend} ${y1}, ${x+bend} ${y2}, ${x} ${y2}`,fill:'none',stroke:palette[r.type],'stroke-width':isSelected?2:1,opacity:isSelected?.55:.1,'stroke-dasharray':r.evidence.key==='T016'?'5 4':'none'});shape('path',{d:`M ${x+7} ${y2-4} L ${x} ${y2} L ${x+7} ${y2+4}`,fill:'none',stroke:palette[r.type],'stroke-width':2,opacity:isSelected?.8:.15});});
  let markerCount=0;rows.filter(r=>r.id).forEach(row=>{const milestones=relevant.filter(e=>e.owners.includes(row.id)).sort((a,b)=>a.date.t-b.date.t),clusters=[];milestones.forEach(e=>{const last=clusters.at(-1);if(last&&scale(e.date.t)-scale(last.at(-1).date.t)<44)last.push(e);else clusters.push([e]);});clusters.forEach((items,clusterIndex)=>{markerCount+=items.length;const x0=scale(items[0].date.t),x1=scale(items.at(-1).date.t),b=el('button',items.length>1?items.length:symbols[items[0].type],'history-node');b.style.left=Math.max(left,x0-16)+'px';b.style.top=(ys.get(row.id)-19)+'px';b.style.width=Math.max(34,x1-x0+34)+'px';b.style.color=palette[items[0].type];b.classList.toggle('month-only',items.every(e=>e.date.monthOnly));b.classList.toggle('muted-node',!!state.selected&&state.selected!==row.id&&!selNeighbors.has(row.id));const label=row.name+'：'+items.map(e=>e.key+' '+e.date.text+' '+e.title).join('；');b.setAttribute('aria-label',label);b.title=label;b.onclick=()=>detail(items,row.name+'的历史节点');canvas.append(b);{const caption=items.length===1?items[0].key+' '+items[0].title:items.length+'条证据 · '+items[0].title;const t=el('span',caption,'history-node-id');t.style.width=Math.max(44,Math.min(180,(clusters[clusterIndex+1]?scale(clusters[clusterIndex+1][0].date.t):width)-x0-7))+'px';t.title=label;t.style.left=Math.max(left,x0-16)+'px';t.style.top=(ys.get(row.id)+16)+'px';canvas.append(t);}});});
  const axis=el('div',null,'history-axis');axis.style.width=width+'px';axis.style.height=header+'px';axis.append(el('span','公司／区位','history-axis-label'));const step=state.range==='all'?6:state.range==='h2'?1:2;for(let t=start;t<=end;t=Date.UTC(new Date(t).getUTCFullYear(),new Date(t).getUTCMonth()+step,1)){const label=el('span',new Date(t).toISOString().slice(0,7),'history-tick');label.style.left=scale(t)+'px';axis.append(label);}canvas.append(axis);
  pinLabels();
  const visible=new Set(rows.filter(r=>r.id).map(r=>r.id)),unknownEvidence=evidence.filter(e=>!e.date&&e.owners.some(id=>visible.has(id)));status.textContent=cs.length+' 个竞争主体 · '+outside.length+' 个关联方／外部主体 · '+rs.length+' 条有日期的关系 · '+unknownEvidence.length+' 条事件日未知证据。节点可点击；公司名称可选择并聚焦。';
  summary.replaceChildren();if(state.selected){const c=companies.get(state.selected);summary.append(el('strong',c?.name||model.partners[state.selected]),el('span',c?'当前板块（分析）：'+sector(c)+'；'+c.route:'关联方，不计为独立竞争者','meta'));const b=el('button','打开该主体完整证据时间轴','btn');b.onclick=()=>detail(evidence.filter(e=>e.owners.includes(state.selected)),(c?.name||model.partners[state.selected])+'证据时间轴');summary.append(b);const relationList=el('div',null,'history-relation-list');relationships.filter(r=>[r.from,r.to].includes(state.selected)).forEach(r=>{const b=el('button',(companies.get(r.from)?.name||model.partners[r.from])+' → '+(companies.get(r.to)?.name||model.partners[r.to])+' · '+r.evidence.date.text+' · '+r.label,'btn');b.onclick=()=>detail([r.evidence],r.label);relationList.append(b);});summary.append(relationList);}else summary.append(el('span','点公司名称后，可查看其完整时间轴及跨板块关系；勾选“聚焦”可缩小到相关公司与伙伴。','meta'));
  gaps.replaceChildren();const undatedCompanies=cs.filter(c=>!relevant.some(e=>e.owners.includes(c.id)));gaps.append(el('p',undatedCompanies.length+' 个所选主体在当前时间窗口没有已知事件日期。不要据此判断成立时间、停业或没有进展。','meta'));unknownEvidence.forEach(e=>{const b=el('button',e.key+' · '+(e.record.company||e.record.name||e.record.subject)+' · '+e.title,'btn');b.onclick=()=>detail([e],'事件日期未知');gaps.append(b);});
 }
 draw();
}
